### Unidad 5, Parte I - Computación III
Carrera Física Aplicada, INSPT UTN<br>
Daiana Dominikow.

## Clase 1: Números Pseudo - Aleatorios
Según Wikipedia, el santo Grial del conocimiento, un número aleatorio es el resultado de una combinación variable al azar que viene dada de una función de distribución.<br>
Pero en la computadora generar un número que sea totalmente aleatorio no es posible, ya que es una máquina determinística, es decir, dado un mismo input vamos a recibir el mismo resultado, y si las condiciones iniciales que pasamos como input se modifican, el resultado también lo hará.<br>
Pero no todo es una tragedia! podemos trabajar con números *pseudoaleatorios* gracias a bibliotecas que facilitan la utilización de algoritmos que pueden devolver distribuciones uniformes de números entre cero y uno, a partir de operaciones matemáticas tras bambalinas que logran determinado fin a partir de una semilla.<br>
Ésta última es un número utilizado para inicializar un generador de números pseudoaleatorios, la semilla no necesariamente debe ser un número aleatorio, aunque determina una secuencia de numeros pseudoaleatorios. En criollo: la misma semilla vá a generara la misma secuencia de números pseudoaleatorios over and over....<br>
Toda este palabrerío se puede resolver sencillamente en Python, que permite pasar una semilla para generar números pseudoaleatorios aunque de manera predeterminada puede inicializarla<br>


In [15]:
#iniciamos importando las bibliotecas de siempre que vamos a utilizar
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime as dt

#### Cómo generamos un número random entre 0 y 1?
Lo hermoso de Numpy, es que nos permite trabajar con números únicos o con arreglos de números, para esto existe la función random() de la clase del mismo nombre.<br>
Si no le pasamos un argumento a esta función, nos vá a devolver un número único entre $[0 y 1)$.<br>
OJO que nunca va a devolver 1, vá a llegar a 0.999999999, pero no incluye al número. (tener este dato en cuenta para el primer ejercicio)<br>

In [22]:
np.random.random()

0.6201313098768588

Pero si queremos un vector de 'n' números random, basta con pasarle por argumento la cantidad 'n' de índices que queremos tenga nuestro vector

In [23]:
n = 25
np.random.random(n)

array([0.05389022, 0.96065406, 0.98042937, 0.52112765, 0.63655334,
       0.76475695, 0.76495529, 0.41768558, 0.76880531, 0.42320175,
       0.92610357, 0.68192648, 0.36845559, 0.85890986, 0.38049568,
       0.09495426, 0.32489071, 0.41511219, 0.74227395, 0.65790887,
       0.20131683, 0.80848791, 0.78640244, 0.39493964, 0.51061623])

### La semilla
Al principio de la ejecución, en general es cuando se setea la semilla que dará lugar a la secuencia de números pseudoaleatoreos. <br>
Durante nuestra ejecución, si llamamos varias veces a la función, veremos distintos números random, aunque sabiendo la semilla, la secuencia en la que estos se generan puede ser totalmente predecible.<br>

In [16]:
#por ejemplo
np.random.seed(42)
print('primer llamado')
print(np.random.random(5))

print('segundo llamado')
print(np.random.random(5))

print('tercer llamado')
print(np.random.random(5))

primer llamado
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
segundo llamado
[0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
tercer llamado
[0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]


In [17]:
#si la inicializo de nuevo, e imprimo un vector de 15 numeros, veremos que sigue la secuencia impresa mas arriba
np.random.seed(42)
print(np.random.random(15))
#fijense que va a devolver los 3 vectores del codigo anterior de corrido. Pruebenlo ustedes!

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985
 0.83244264 0.21233911 0.18182497]


Entonces, sabemos que si nosotros reseteamos la semilla en cada ejecución, el generador de números random siempre nos vá a devolver la misma secuencia de números.<br>

In [18]:
#por ejemplo
np.random.seed(42)
print('primer llamado')
print(np.random.random(5))

np.random.seed(42)
print('segundo llamado')
print(np.random.random(5))

np.random.seed(42)
print('tercer llamado')
print(np.random.random(5))

primer llamado
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
segundo llamado
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
tercer llamado
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


### Buenas prácticas
Una buena práctica a la hora de trabajar con números random es cambiar, de manera automática, la semilla que los genera.<br>
Para esto existen múltiples métodos, siendo el mas sencillo inicializar el script con una semilla a partir del momento de ejecución, es decir, podemos agarrar los minutos y segundos de ejecución y a partir de ahí cada vez que ejecute el script la semilla irá cambiando.<br>

In [19]:
minutos = dt.now().minute
segundos = dt.now().second
print(f'minuto:{minutos}, segundos: {segundos}')

#entonces inicializamos nuestra semilla con la suma de estos numeros en cada ejecución
np.random.seed(minutos+segundos)
print(np.random.random(5))

minuto:17, segundos: 25
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [20]:
#esto es para que mi ejecución banque un toque, para el ejemplo  :)
import time
time.sleep(10)

In [21]:
##vamos a repetirlo para probar el generador de semilla random a partir del minuto segundo de ejecución
minutos = dt.now().minute
segundos = dt.now().second
print(f'minuto:{minutos}, segundos: {segundos}')
np.random.seed(minutos+segundos)
print(np.random.random(5))

minuto:17, segundos: 35
[0.82311034 0.02611798 0.21077064 0.61842177 0.09828447]


### Ahora... si quisiera un intervalo de números diferente? 
Por ejemplo, de cero a 10?<br>
Bueno, para esto basta con multiplicar nuestro número random por 10, tan sencillo como 

In [24]:
np.random.random(n)*10

array([7.96159542, 4.45377496, 7.43066911, 0.78749073, 4.87645258,
       4.34388645, 2.46057946, 8.61640718, 0.20022559, 4.5082671 ,
       0.47422874, 4.97727496, 8.58774004, 3.34815656, 9.01590031,
       1.22887554, 1.57433747, 7.87385292, 6.64939058, 7.20204172,
       5.39255323, 4.71947454, 9.00687504, 3.74512511, 5.27786445])

#### Pero si quiero  (por ejemplo) un intervalo que vaya de 5 a 10, se nos complica un poco:<br>
Primero debemos tener en cuenta que la función nos vá a devolver un valor entre 0 y 1, que debemos transformar a valores que vayan el 5 al 10<br>
Ya vimos que si queremos que llegue hasta el 5, debemos multiplicar el valor que devuelve la función por aquella cota<br>
En caso de que la función valga 0, nuestro número debería ser 5, así que a la función debemos sumarle 5<br>

In [25]:
np.random.random(n) * 5 + 5

array([8.47246712, 7.12784131, 8.1928834 , 7.97162342, 7.2714049 ,
       9.57888208, 8.72033701, 9.64742901, 9.45588995, 6.60166603,
       8.45013174, 5.29434039, 6.00891932, 8.61530883, 8.76004962,
       6.47690564, 9.7922346 , 5.02181637, 6.7487107 , 5.98741185,
       7.18794256, 9.64807834, 6.40122741, 7.1394195 , 7.32582481])

### El algoritmo para cualquier distribución de números random lo podríamos escribir como<br>
$random * (fin - inicio) + inicio$

In [26]:
#ejemplo, quiero una distribución entre -2 y 2
inicio = -2
fin = 2
np.random.random(n) * ( fin - inicio ) + inicio 

array([ 1.42049526,  1.93754737, -0.08908974,  0.14681745,  1.12881833,
        1.25930107, -1.41737946, -0.62708135,  0.78247961, -1.24712248,
       -0.17830123,  1.88169232,  1.97738316,  1.00203351,  0.04915558,
        0.05908935, -1.72331147,  1.88472946,  1.81928163,  1.12006522,
        1.39397854, -0.40253718,  1.18769543, -1.92931714, -1.33022498])

#### Empecemos entonces con la práctica de números aleatorios  (TP 6) para entender un poco de que se trata todo esto<br>


## Consignas TP 6: números peudoaleatoreos, Parte I.
0. Cree dos vectores de 1000 números random entre -250 y 250, a continuación plotee una distribucion con los valores que obtuvo. Qué puede observar?<br><br>
1. Calcule la probabilidad de obtener un número 'x' luego de 'n' veces de lanzar un dado, para ello guarde los valores de cada tirada en una lista, y cree una función que dada esa lista y el número a buscar, devuelva el % de veces que se obtuvo dicho número.<br>
Por otro lado realice un histograma con los resultados, qué conclusiones puede sacar viendo dicho histograma a medida que varía 'n'?, pruebe con 100, 1000 y 10000 ejecuciones.<br>
Para plotear el histograma utilice la función plt.hist(vector, bins = 48), donde bins es la cantidad de divisiones del histograma.<br>